name: First-Grid
favicon: null
layout_spectrum: 0.5255311238579452
typography_spectrum: 0.24629109911620617
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.3635197707917541
  lightness: 0.48931568022817373
  saturation: 0.14583298307843506
  rhythmicContrast: 0.8560005081817508
purpose: []
